### PR TITLE
New pull

### PR DESCRIPTION
**Pull request by StefanoMartin**
I continue to work on this gem. :+1: 

- Deleted URI function
- Simplified create_general_class
- Add possibility to addd properties in the creation of a class
- Add alter_property (useful for MIN or MAX)
- Deleted Camelize and put the rules that the classes needs to be capitalized
- Modified README.md
- Updated examples

### CODE REVIEW

**Comment by topofocus** [comment]
Hi, looks great. Would you like to get the right to merge by yourself?

**Comment by topofocus** [comment]
Perhaps its time to raise the version in the gem, too. What do you think?

**Comment by StefanoMartin** [comment]
It would be nice to have the right to merge. Thanks! :+1: 

It is fine for me to raise the version of the gem. I tried my and your examples and they seems to work.

Note that your original version permitted not capitalized classes (since you used camelize), at the contrary this updated version does not permit any more not capitalized classes. Some people can have some problem of compatibility.
I preferred to remove "camelize" since it was not nice to have two different name for the same data in the code and in the database.

**Comment by topofocus** [comment]
added you as  Collaborator.
Hope that's enough.

You can contact me directly via topofocus@gmail.com,  via email and hangout.

greetings from Stuttgart

hartmut

2016-04-06 13:29 GMT+02:00 Stefano <notifications@github.com>:

> It would be nice to have the right to merge. Thanks! [image: :+1:]
>
> It is fine for me to raise the version of the gem. I tried my and your
> examples and they seems to work.
>
> Note that your original version permitted not capitalized classes (since
> you used camelize), at the contrary this updated version does not permit
> any more not capitalized classes. Some people can have some problem of
> compatibility.
> I preferred to remove "camelize" since it was not nice to have two
> different name for the same data in the code and in the database.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/topofocus/active-orient/pull/8#issuecomment-206322706>
>



-- 
finanz coaching
Dr. Hartmut Bischoff
Stuttgart
( http://ficoach.de)

**Pull request merged**
